openapi: 3.0.3
info:
  title: Rate Limiter API
  version: 1.0.0
  description: Contract for creating and managing rate limit rules.

servers:
  - url: http://localhost:8080

paths:
  /ratelimiter:
    $ref: './paths.yaml#/rateLimitRule'
  /ratelimiter/validate:
    $ref: './paths.yaml#/validateRateLimit'
  /ratelimiter/{id}:
    $ref: './paths.yaml#/rateLimitRuleById'

components:
  schemas:
    ApiSignature:
      $ref: './definitions.yaml#/ApiSignature'
    CreateRateLimitRuleRequest:
      $ref: './definitions.yaml#/CreateRateLimitRuleRequest'
    CreateRateLimitRuleResponse:
      $ref: './definitions.yaml#/CreateRateLimitRuleResponse'
    GetRateLimitRuleResponse:
      $ref: './definitions.yaml#/GetRateLimitRuleResponse'
    RateLimitRuleDuration:
      $ref: './definitions.yaml#/RateLimitRuleDuration'
    RateLimitValidateResponse:
      $ref: './definitions.yaml#/RateLimitValidateResponse'
